cache_file_location = "~/.config/themester/.themecache"

term_env_var_name = "TERM_THEME"
nvim_plugin_env_var_name = "NVIM_THEME_PLUGIN"
nvim_theme_env_var_name = "NVIM_THEME"

write_term_lua = true
term_lua_path = "~/.config/wezterm/dynamic_theme.lua"

hours_per_randomization = 1

[[theme]]
term = "Tokyo Night"
nvim_plugin = "tokyonight"
nvim_themename = "tokyonight-night"

[[theme]]
term = "Tokyo Night Moon"
nvim_plugin = "tokyonight"
nvim_themename = "tokyonight-moon"

[[theme]]
term = "Tokyo Night Storm"
nvim_plugin = "tokyonight"
nvim_themename = "tokyonight-storm"

[[theme]]
term = "Tokyo Night (Gogh)"
nvim_plugin = "tokyodark"
nvim_themename = "tokyodark"

[[theme]]
term = "Poimandres Storm"
nvim_plugin = "poimandres"
nvim_themename = "poimandres"

[[theme]]
term = "Oceanic-Next"
nvim_plugin = "oceanic-next"
nvim_themename = "OceanicNext"

[[theme]]
term = "nordfox"
nvim_themename = "oh-lucy"

[[theme]]
term = "nordfox"
nvim_themename = "oh-lucy-evening"

[[theme]]
term = "catppuccin-frappe"
nvim_plugin = "catppuccin"
nvim_themename = "catppuccin-frappe"

[[theme]]
term = "catppuccin-macchiato"
nvim_plugin = "catppuccin"
nvim_themename = "catppuccin-macchiato"

[[theme]]
term = "catppuccin-mocha"
nvim_plugin = "catppuccin"
nvim_themename = "catppuccin-mocha"

[[theme]]
term = "GruvboxDark"
nvim_themename = "gruvbox-material"

[[theme]]
term = "Gruvbox Dark (Gogh)"
nvim_themename = "gruvbox-material"

[[theme]]
term = "nightfox"
nvim_plugin = "nightfox"
nvim_themename = "nightfox"

[[theme]]
term = "nordfox"
nvim_plugin = "nightfox"
nvim_themename = "nordfox"

[[theme]]
term = "nordfox"
nvim_plugin = "nightfox"
nvim_themename = "terafox"

[[theme]]
term = "rose-pine"
nvim_plugin = "rose-pine"
nvim_themename = "rose-pine"

[[theme]]
term = "Kanagawa (Gogh)"
nvim_plugin = "kanagawa"
nvim_themename = "kanagawa-wave"

# [[theme]]
# term = "Kanagawa Dragon (Gogh)"
# nvim_plugin = "kanagawa"
# nvim_themename = "kanagawa-dragon"

[[theme]]
term = "Everblush"
nvim_plugin = "everblush"
nvim_themename = "everblush"

[[theme]]
term = "Sonokai (Gogh)"
nvim_plugin = "none"
nvim_themename = "sonokai"

[[theme]]
term = "Edge Dark (base16)"
nvim_plugin = "none" # none
nvim_themename = "edge"

# [[theme]]
# term = "Firewatch"
# nvim_plugin = "flow"
# nvim_themename = "flow"

# [[theme]]
# term = "Solarized Dark (Gogh)"
# nvim_plugin = "solarized-osaka"
# nvim_themename = "solarized-osaka"

# [[theme]]
# term = "kanagawabones"
# nvim_plugin = "kanagawa-paper"
# nvim_themename = "kanagawa-paper"
