-- replaced by proper themester plugin, no longer loaded
-- local plug = os.getenv("NVIM_THEME_PLUGIN") or "nightfox"
-- local theme = os.getenv("NVIM_THEME") or "nightfox"
--
-- if plug ~= "none" then
--     require(plug).setup({})
-- end
-- vim.cmd("colorscheme " .. theme)
-- require("notify")(theme)
