local wk = require("which-key")

wk.add({
    { "<leader>b", group = "Buffers" },
    { "<leader>C", group = "Case conversion" },
    { "<leader>Cl", group = "LSP rename" },
    { "<leader>D", group = "Tests" },
    { "D", group = "Debugger", mode = "n" },
    { "<leader>e", group = "Edit" },
    { "<leader>f", group = "Files" },
    { "<leader>g", group = "Git" },
    { "<leader>h", group = "History" },
    { "<leader>i", group = "Indentation" },
    { "<leader>l", group = "LSP", mode = { "n", "x" } },
    { "<leader>lc", group = "Call hierarchy" },
    { "<leader>lS", group = "Scope" },
    { "<leader>lg", group = "Goto / type hierarchy" },
    { "<leader>ls", group = "Symbols / show" },
    { "<leader>lw", group = "Workspace" },
    { "<leader>ly", group = "Hierarchy (Meow Yarn)" },
    { "<leader>m", group = "Format / lint", mode = { "n", "x" } },
    { "<leader>q", group = "Quickfix" },
    { "<leader>s", group = "Search / pick", mode = { "n", "x" } },
    { "<leader>t", group = "Toggles" },
    { "<leader>u", group = "UI" },
    { "<leader>x", group = "Trouble" },
    { "X", group = "Xcodebuild", mode = "n" },
    { "Xd", group = "Debug" },
    { "s", group = "Hop", mode = { "n", "x", "o" } },
})
