local wk = require("which-key")

wk.add({
    { "<leader>b", group = "Buffers" },
    { "<leader>C", group = "Case conversion" },
    { "<leader>Cl", group = "LSP rename" },
    { "<leader>D", group = "Debug" },
    { "<leader>Dn", group = "Tests" },
    { "<leader>Ds", group = "Step" },
    { "<leader>e", group = "Edit" },
    { "<leader>ea", group = "Arguments" },
    { "<leader>f", group = "Files" },
    { "<leader>g", group = "Git" },
    { "<leader>h", group = "History" },
    { "<leader>i", group = "Indentation" },
    { "<leader>l", group = "LSP", mode = { "n", "x" } },
    { "<leader>lc", group = "Calls" },
    { "<leader>lS", group = "Scope" },
    { "<leader>lg", group = "Goto" },
    { "<leader>ls", group = "Show" },
    { "<leader>lw", group = "Workspace" },
    { "<leader>m", group = "Format / lint", mode = { "n", "x" } },
    { "<leader>q", group = "Quickfix" },
    { "<leader>s", group = "Search / pick", mode = { "n", "x" } },
    { "<leader>sc", group = "Namu calls" },
    { "<leader>t", group = "Toggles" },
    { "<leader>u", group = "UI" },
    { "<leader>x", group = "Trouble" },
    { "<leader>xc", group = "Code" },
    { "<leader>X", group = "Xcodebuild", mode = { "n", "x" } },
    { "<leader>Xd", group = "Debug" },

    { "s", group = "Hop", mode = { "n", "x", "o" } },
})
