monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-046d_HD_Pro_Webcam_C920_3A26D59F-02"
      }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  },
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_26_00.1"
      }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  },
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_2e_00.4"
      }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  }
]
