# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]
1 = ['U2718Q', 'BenQ']
2 = 'P2723QE'
3 = 'built-in'
4 = ['U2718Q', 'BenQ']
5 = 'P2723QE'
6 = 'built-in'
7 = ['U2718Q', 'BenQ']
8 = 'P2723QE'
9 = 'built-in'

[mode.main.binding]
cmd-tab = 'workspace-back-and-forth'
cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

#cmd-enter = 'exec-and-forget open -n /System/Applications/Alacritty.app'

cmd-left = 'focus left'
cmd-down = 'focus down'
cmd-up = 'focus up'
cmd-right = 'focus right'

cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

# cmd-h = 'split horizontal'
# cmd-v = 'split vertical'

cmd-f = 'fullscreen'

cmd-s = 'layout v_accordion' # 'layout stacking' in i3
cmd-shift-a = 'layout h_accordion' # 'layout tabbed' in i3
cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

cmd-w = 'exec-and-forget open -n /Applications/Zen\ Browser.app'
cmd-enter = 'exec-and-forget open -n /Applications/WezTerm.app'
# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#cmd-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# cmd-a = 'focus parent'
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

cmd-ctrl-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-ctrl-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-ctrl-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-ctrl-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-ctrl-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
cmd-ctrl-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
cmd-ctrl-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
cmd-ctrl-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
cmd-ctrl-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'

cmd-shift-c = 'reload-config'

cmd-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = ['layout floating']  # The callback itself
